before_script:
- apt-get update -qq
- apt-get install -y -qq python3.5

my-job:
  script:
  - python3.5 build.py sync
  - python3.5 build.py build-linux x64 debug
  artifacts:
    paths:
    - build
    expire_in: 4 mos

