version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image: Visual Studio 2017

configuration:
- release
- debug

environment:
  matrix:
  - V8_TARGET_ARCH: x64
  - v8_TARGET_ARCH: ia32

init:
- cmd: echo %V8_TARGET_ARCH% %configuration%

before_build:
- cmd: python -m pip install -U pip
- cmd: python -m pip install pywin32
- cmd: C:\Python35-x64\python.exe build.py sync

build_script:
- cmd: C:\Python35-x64\python.exe build.py build-windows %V8_TARGET_ARCH% %configuration%

deploy_script:
- cmd: dir build\%V8_TARGET_ARCH%\%configuration%
- cmd: dir build\%V8_TARGET_ARCH%\%configuration%\obj
#- cmd: C:\Python35-x64\python.exe build.py deploy-windows %V8_TARGET_ARCH% %Configuration%

artifacts:
- path: build
- name: build-$(V8_TARGET_ARCH)_$(configuration)

