version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image: Visual Studio 2013

configuration:
- Release
- Debug

environment:
  matrix:
    - V8_TARGET_ARCH: x64
    
    - v8_TARGET_ARCH: ia32

init:
- cmd: echo %V8_TARGET_ARCH% %Configuration%

install:

before_build:
- cmd: C:\Python35-x64\python.exe build.py sync

build_script:
- cmd: C:\Python35-x64\python.exe build.py build-windwos %V8_TARGET_ARCH% /p:%Configuration%

deploy: off
