version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image: Visual Studio 2013

configuration:
- Release
- Debug

environment:
  global:
    DEPLOYMENT_PERSONAL_ACCESS_TOKEN:
      secure: qT/U8FGBtZM5qwvGtuASXXbHhl3R6w2R5YEBkc09E+RT6SsgPnhHoLQOsomh3ADP
  matrix:
  - V8_TARGET_ARCH: x64
    
  - v8_TARGET_ARCH: ia32

init:
- cmd: echo %V8_TARGET_ARCH% %Configuration%

before_build:
- cmd: C:\Python35-x64\python.exe build.py sync

build_script:
- cmd: C:\Python35-x64\python.exe build.py build-windows %V8_TARGET_ARCH% %Configuration%

deploy_script:
- cmd: C:\Python35-x64\python.exe build.py deploy-windows %V8_TARGET_ARCH% %Configuration%
