version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_V8: linux
    V8_TARGET_ARCH: x64
    configuration: debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_V8: android
    V8_TARGET_ARCH: arm
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_V8: android
    V8_TARGET_ARCH: arm64
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_V8: android
    V8_TARGET_ARCH: ia32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    V8_TARGET_ARCH: x64
    configuration: release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    V8_TARGET_ARCH: x64
    configuration: debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    v8_TARGET_ARCH: ia32
    configuration: release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    v8_TARGET_ARCH: ia32
    configuration: debug

init:
- cmd: echo %V8_TARGET_ARCH% %configuration%
- sh: echo ${V8_TARGET_ARCH} ${configuration}
- sh: df -h

before_build:
- cmd: python -m pip install -U pip
- cmd: python -m pip install pywin32
- cmd: C:\Python35-x64\python.exe build.py sync
- sh: python3.5 build.py sync

build_script:
- cmd: C:\Python35-x64\python.exe build.py build-windows %V8_TARGET_ARCH% %configuration%
- sh: python3.5 build.py build-${BUILD_V8} ${V8_TARGET_ARCH} ${configuration}

deploy_script:
- cmd: dir build\%V8_TARGET_ARCH%\%configuration%
- cmd: dir build\%V8_TARGET_ARCH%\%configuration%\obj
- sh: ls build
#- cmd: C:\Python35-x64\python.exe build.py deploy-windows %V8_TARGET_ARCH% %Configuration%

artifacts:
- path: build
  name: build-$(V8_TARGET_ARCH)_$(configuration)
  type: zip

